### ISSUE TITLE
Continue maintaining?

### ISSUE THREAD

**Issue by eisengrau** [radokristof/HunFakeNewsAdblockList#1]
Hello,

I am curious if you have time to maintain this list? If you need help, I will gladly assist as I can.

Köszi,

**Comment by radokristof** [comment]
Hello!
I'm still trying to maintain this list, however I usually used articles which contained these domains and parsed the domains from it.
If you found any new domain which is not contained in the list, you can create a PR and I happily merge it, or just throw the domains here.

**Comment by radokristof** [comment]
Also I had some domains which was not commited, now I did it.

I mean I used articles like this: (however they only make these articles once a year...).
https://www.urbanlegends.hu/2020/01/megteveszto-magyar-hiroldalak-listaja-2020/

**Comment by eisengrau** [comment]
Awesome, thank you, and for your quick reply!

Sure thing, I'll try to look out for any shady domains and will keep it updated here, nevertheless. Fortunately I am not really active on social media any more (these things tend to pop-up on Facebook a lot) so I really can't keep up with these, however I would keep on protecting my family (shared pi-hole instance) from shady websites, of course.

Thank You,
LM,
