### ISSUE TITLE
Frissítés

### ISSUE THREAD

**Issue by Zsombe** [radokristof/HunFakeNewsAdblockList#2]
Szia!
Ez a lista ha jól látom két éve frissült utoljára. Azóta nincs több időd foglalkozni vele, vagy szimplán nincs több új fakenews oldal?

**Comment by radokristof** [comment]
Szia! Meglévő listákból szedtem ezeket össze, azokat többször is néztem, nem volt újabb változat.
Most láttam, hogy van egy újabb adatbázis ami ilyen oldalakat tartalmaz: https://www.urbanlegends.hu/forraselemzes/

A nagy része már benn van a listában ahogy nézem, de a hetekben majd ez alapján frissítem a listát.

**Comment by Zsombe** [comment]
Köszönöm!

Esetleg még ez a blogbejegyzésem segítségedr lehet: https://zsombe.com/bejegyzesek/fakenews-oldalak/
Remélem hamarosan frissül a lista, vagy szívesen segítek is benne. :)

**Comment by radokristof** [comment]
Nagyon jó, köszi :) ezeket is bele fogom venni, amelyik még nincs benne a listában.

**Comment by radokristof** [comment]
@Zsombe frissítettem a hosts file-t mindkét helyről az új domain-ekkel.

**Comment by Zsombe** [comment]
> 

Köszönöm!
